### ISSUE TITLE
Use Template literals (String Interpolation)

### ISSUE THREAD

**Issue by brenopolanski** [AshleyScirra/scirra-offline-sw#2]
Template literals are string literals allowing embedded expressions. You can use multi-line strings and string interpolation features with them.

#### ES5

```
function GetCacheBaseName()
{
	return CACHE_NAME_PREFIX + "-" + self.registration.scope;
};
```

#### ES6

```
function GetCacheBaseName()
{
	return `${CACHE_NAME_PREFIX}-${self.registration.scope}`;
};
```

**Reference**: http://es6-features.org/#StringInterpolation

**Comment by AshleyScirra** [comment]
Template literals have their uses, but I don't think this kind of case is clearly better. It seems like using features for the sake of it.

**Comment by brenopolanski** [comment]
Okay.. but create multiple strings and then concatenating them uses more memory and is slower than creating a single string one time.

**Comment by AshleyScirra** [comment]
JS engines have really good optimizers for this kind of thing. Citation needed! Also in that function, performance is not a significant concern.

**Comment by brenopolanski** [comment]
Okay.. no problems :smile:
